# Generated by Django 5.2.4 on 2025-07-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One_Step_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
