# Generated by Django 5.2.4 on 2025-07-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One_Step_Shop', '0004_choice_product_created_at_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='One_Step_Shop.category'),
        ),
    ]
