# Generated by Django 5.2.4 on 2025-07-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       ('One_Step_Shop', '0005_category_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
